# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=20, null=True)),
                ('quarter', models.CharField(blank=True, max_length=20, null=True)),
                ('stk_code', models.CharField(blank=True, max_length=50, null=True)),
                ('stk_name', models.CharField(blank=True, max_length=50, null=True)),
                ('roe', models.CharField(blank=True, max_length=50, null=True)),
                ('netmargin', models.CharField(blank=True, max_length=50, null=True)),
                ('grossmargin', models.CharField(blank=True, max_length=50, null=True)),
                ('netprofit', models.CharField(blank=True, max_length=50, null=True)),
                ('eps', models.CharField(blank=True, max_length=50, null=True)),
                ('imcome', models.CharField(blank=True, max_length=50, null=True)),
                ('imcompershare_field', models.CharField(blank=True, db_column='imcompershare ', max_length=50, null=True)),
            ],
            options={
                'db_table': 'profit',
                'managed': False,
            },
        ),
    ]
